import * as APIUtil from '../util/like_api_util';

export const RECEIVED_ALL_TRACK_LIKES = 'RECEIVED_ALL_TRACK_LIKES';
export const RECEIVED_TRACK_LIKE = 'RECEIVED_TRACK_LIKE';
export const REMOVED_TRACK_LIKE = 'REMOVED_TRACK_LIKE';

export const RECEIVED_ALL_ALBUM_LIKES = 'RECEIVED_ALL_ALBUM_LIKES';
export const RECEIVED_ALBUM_LIKE = 'RECEIVED_ALBUM_LIKE';
export const REMOVED_ALBUM_LIKE = 'REMOVED_ALBUM_LIKE';